Numpy - Numerical Python
1. It has wide variety of mathematical operations
2. It is faster

In [2]:
import numpy as np

In [8]:
from time import process_time

**Faster**

In [6]:
#List
py_list = [i for i in range(10000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.0011726900000006424


In [9]:
#Numpy
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.000884572000000361


**NUMPY ARRAY**

In [11]:
#list
list1 = [1,2,3,4]
print(type(list1))

np_array = np.array([1,2,3,4])
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
#1 dim array
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [18]:
#2 dimension
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [20]:
#3 dimension
c = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(c)
print(c.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [23]:
#create a numpy array with only zeros
#np.zeros((rows,column))
d = np.zeros((4,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
#create a numpy array with only ones
#np.ones((rows,column))
e = np.ones((4,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
#create a numpy array with any 1 value
#np.full((rows,column),element)
f = np.full((4,3),2)
print(f)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [30]:
#identity matrix
#no.eye(row/column)
g = np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#create a numpy array with random values
#np.random.random((row,column))
h = np.random.random((3,4))
print(h)

[[0.89892926 0.15136772 0.54319477 0.82055257]
 [0.60761435 0.85837553 0.66859743 0.39429221]
 [0.51579224 0.91249148 0.17851657 0.92182898]]


In [40]:
#random values in int format
#np.random.randint(start,end,(row,column))
i = np.random.randint(10,100,(3,5))
print(i)

[[63 83 32 53 68]
 [77 60 48 61 76]
 [71 34 87 63 23]]


In [45]:
# Array of evenly spaced values
#np.linspace(start,end,specify number of values needed)
j = np.linspace(10,30,5)
print(j)

[10. 15. 20. 25. 30.]


In [52]:
## Array of evenly spaced values - specifying the step
#np.arange(start,end,skip)
k = np.arange(10,30,3)
print(k)

[10 13 16 19 22 25 28]


In [54]:
#list to np.array
list2 = [10,20,30,40,50]

#np.asarray(variable of list)
l = np.asarray(list2)
type(l)

numpy.ndarray

**Analysing a numpy array**

In [58]:
ck = np.random.randint(10,90,(4,5))
ck

array([[24, 13, 57, 52, 47],
       [54, 59, 32, 89, 12],
       [37, 61, 87, 49, 10],
       [30, 20, 17, 30, 67]])

In [60]:
#array dimension
print(ck.shape)

(4, 5)


In [62]:
#number of elements in an array
print(ck.size)

20


In [64]:
#identify the data type in np array
print(ck.dtype)

int64


**mathematical Operations**

In [67]:
mat1 = np.random.randint(0,10,(3,3))
mat2 = np.random.randint(10,20,(3,3))
print(mat1)
print(mat2)

[[2 8 4]
 [4 3 2]
 [7 4 3]]
[[19 14 17]
 [14 14 14]
 [11 10 16]]


In [70]:
print(mat1 + mat2)

[[21 22 21]
 [18 17 16]
 [18 14 19]]


In [72]:
print(mat1 - mat2)

[[-17  -6 -13]
 [-10 -11 -12]
 [ -4  -6 -13]]


In [74]:
print(mat1*mat2)

[[ 38 112  68]
 [ 56  42  28]
 [ 77  40  48]]


In [76]:
print(mat1/mat2)

[[0.10526316 0.57142857 0.23529412]
 [0.28571429 0.21428571 0.14285714]
 [0.63636364 0.4        0.1875    ]]


**Transpose**

In [79]:
mat3 = np.random.randint(0,10,(2,3))
print(mat3)
print(mat3.shape)

[[2 1 8]
 [5 3 7]]
(2, 3)


In [80]:
trans = np.transpose(mat3)
print(trans)
print(trans.shape)

[[2 5]
 [1 3]
 [8 7]]
(3, 2)
